name: EvilBook
main: com.amentrix.evilbook.main.EvilBook
version: 6.1.5
depend: [dynmap, ProtocolLib, EvilBook-Logging]
commands:
  alt:
    description: Get a list of possible alts with the same ip as a player
    usage: /<command> [playerName]
  ip:
    description: Get the last known ip of a player
    usage: /<command> [playerName]
  map:
    description: Create a map
    usage: /<command>
  drug:
    description: Spawns a drug
    usage: /<command> [drug]
  cut:
    description: Cut a selection of blocks into the clipboard
    usage: /<command> [count] [axis]
  /cut:
    description: Cut a selection of blocks into the clipboard
    usage: /<command> [count] [axis]
  move:
    description: Move a selection of blocks
    usage: /<command> [count] [axis]
  /move:
    description: Move a selection of blocks
    usage: /<command> [count] [axis]
  thaw:
    description: Thaw snow cover
    usage: /<command>
  snow:
    description: Simulate snow cover
    usage: /<command>
  title:
    description: Set the player's title
    usage: /<command> [title]
  flip:
    description: Flip an area of blocks
    usage: /<command> [axis]
  /flip:
    description: Flip an area of blocks
    usage: /<command> [axis]
  more:
    description: Turn the item stack into your hand to a full item stack
    usage: /<command>
  hyperhorse:
    description: Hyper horse
    usage: /<command>
  mail:
    description: Handle mail commands
    usage: /<command>
  drwatson:
    description: Execute Dr. Watson server cleaning
    usage: /<command>
  oldcreative:
    description: Teleport to the old creative world
    usage: /<command>
  hub:
    description: Teleport to the world hub
    usage: /<command>
  minigame:
    description: Preform minigame actions
    usage: /<command>
  reply:
    description: Reply to the last message recieved or sent
    usage: /<command>
  r:
    description: Reply to the last message recieved or sent
    usage: /<command>
  setbiome:
    description: Set the biome of the selected evil edit blocks
    usage: /<command>
  /setbiome:
    description: Set the biome of the selected evil edit blocks
    usage: /<command>
  troll:
    description: Secret
    usage: /<command>
  tool:
    description: Changes the player's edit wand mode
    usage: /<command>
  effect:
    description: Adds an effect emitter to the world
    usage: /<command> [effect] <frequency> <amount>
  chimney:
    description: Creates a chimney
    usage: /<command>
  count:
    description: Sends the player the number of certain blocks in their eviledit selection
    usage: /<command>
  /count:
    description: Sends the player the number of certain blocks in their eviledit selection
    usage: /<command>
  size:
    description: Sends the player the size of their eviledit selection
    usage: /<command>
  /size:
    description: Sends the player the size of their eviledit selection
    usage: /<command>
  toggleeditwand:
    description: Toggles the players evil edit wand
    usage: /<command>
  statistics:
    description: Views the server statistics
    usage: /<command>
  stats:
    description: Views the server statistics
    usage: /<command>
  world:
    description: Teleport to a private world
    usage: /<command>
  achievements:
    description: View the player achievements
    usage: /<command>
  ach:
    description: View the player achievements
    usage: /<command>
  rreplace:
    description: Randomly replace blocks in a selected area
    usage: /<command>
  rfill:
    description: Randomly fill blocks in a selected area
    usage: /<command>
  rdel:
    description: Randomly delete blocks in a selected area
    usage: /<command>
  rdelete:
    description: Randomly delete blocks in a selected area
    usage: /<command>
  deletewarp:
    description: Delete a warp
    usage: /<command> [warp]
  delwarp:
    description: Delete a warp
    usage: /<command> [warp]
  remwarp:
    description: Delete a warp
    usage: /<command> [warp]
  rmwarp:
    description: Delete a warp
    usage: /<command> [warp]
  desel:
    description: Deselect the player evil edit selection
    usage: /<command>
  /desel:
    description: Deselect the player evil edit selection
    usage: /<command>
  wand:
    description: Spawn the player an evil edit wand
    usage: /<command>
  /wand:
    description: Spawn the player an evil edit wand
    usage: /<command>
  thru:
    description: Pass the player through the object infront of them
    usage: /<command>
  ceil:
    description: Ascend the player to the ceiling
    usage: /<command>
  descend:
    description: Descend the player to the next free block
    usage: /<command>
  ascend:
    description: Ascend the player to the next free block
    usage: /<command>
  setrank:
    description: Set the player's custom rank
    usage: /<command>
  pumpkins:
    description: Generate a pumpkin forest
    usage: /<command>
  forest:
    description: Generate a forest
    usage: /<command>
  forestgen:
    description: Generate a forest
    usage: /<command>
  hcylinder:
    description: Generate a hollow cylinder
    usage: /<command>
  /hcylinder:
    description: Generate a hollow cylinder
    usage: /<command>
  cylinder:
    description: Generate a filled cylinder
    usage: /<command>
  /cylinder:
    description: Generate a filled cylinder
    usage: /<command>
  hcyl:
    description: Generate a hollow cylinder
    usage: /<command>
  /hcyl:
    description: Generate a hollow cylinder
    usage: /<command>
  cyl:
    description: Generate a filled cylinder
    usage: /<command>
  /cyl:
    description: Generate a filled cylinder
    usage: /<command>
  hpyramid:
    description: Generate a hollow pyramid
    usage: /<command>
  /hpyramid:
    description: Generate a hollow pyramid
    usage: /<command>
  pyramid:
    description: Generate a filled pyramid
    usage: /<command>
  /pyramid:
    description: Generate a filled pyramid
    usage: /<command>
  esphere:
    description: Generate an empty hollow sphere
    usage: /<command>
  /esphere:
    description: Generate an empty hollow sphere
    usage: /<command>
  hsphere:
    description: Generate a hollow sphere
    usage: /<command>
  /hsphere:
    description: Generate a hollow sphere
    usage: /<command>
  sphere:
    description: Generate a filled sphere
    usage: /<command>
  /sphere:
    description: Generate a filled sphere
    usage: /<command>
  creative:
    description: Teleport to the main creative world
    usage: /<command>
  survival:
    description: Teleport to the survival world
    usage: /<command>
  jump:
    description: Set the player jump height
    usage: /<command> [height]
  drain:
    description: Drain an area of blocks
    usage: /<command>
  /drain:
    description: Drain an area of blocks
    usage: /<command>
  green:
    description: Turn an area of blocks from dirt to grass
    usage: /<command>
  /green:
    description: Turn an area of blocks from dirt to grass
    usage: /<command>
  regen:
    description: Regenerate an area of blocks
    usage: /<command>
  /regen:
    description: Regenerate an area of blocks
    usage: /<command>
  hollow:
    description: Hollow an area of blocks
    usage: /<command>
  /hollow:
    description: Hollow an area of blocks
    usage: /<command>
  outline:
    description: Outline an area of blocks
    usage: /<command>
  /outline:
    description: Outline an area of blocks
    usage: /<command>
  walls:
    description: Wall an area of blocks
    usage: /<command>
  /walls:
    description: Wall an area of blocks
    usage: /<command>
  overlay:
    description: Overlay an area of blocks
    usage: /<command>
  /overlay:
    description: Overlay an area of blocks
    usage: /<command>
  paste:
    description: Paste an area of blocks
    usage: /<command>
  /paste:
    description: Paste an area of blocks
    usage: /<command>
  copy:
    description: Copy an area of blocks
    usage: /<command>
  /copy:
    description: Copy an area of blocks
    usage: /<command>
  replace:
    description: Replace an area of blocks with another block
    usage: /<command> [blockID] [blockID]
  /replace:
    description: Replace an area of blocks with another block
    usage: /<command> [blockID] [blockID]
  speed:
    description: Set the player speed limits
    usage: /<command> <walk|run|fly> <speed>
  accept:
    description: Accept a teleport request
    usage: /<command>
  disguise:
    description: Disguise the player as another entity
    usage: /<command>
  name:
    description: Rename the held item
    usage: /<command> [name]
  skull:
    description: Set the owner of a held skull or new skull
    usage: /<command> [owner]
  advertise:
    description: Broadcast an advertisement
    usage: /<command> [message]
  advert:
    description: Broadcast an advertisement
    usage: /<command> [message]
  helmet:
    description: Sets the players helmet to the block they're holding
    usage: /<command>
  hat:
    description: Sets the players helmet to the block they're holding
    usage: /<command>
  head:
    description: Sets the players helmet to the block they're holding
    usage: /<command>
  butter:
    description: Gives a player butter
    usage: /<command>
  region:
    description: Preform region operation
    usage: /<command>
  req:
    description: Request admin assistance
    usage: /<command> [message]
  helpop:
    description: Request admin assistance
    usage: /<command> [message]
  stop:
    description: Stop the server
    usage: /<command> [message]
  givemoney:
    description: Transfer money to another player
    usage: /<command> [player] [amount]
  pay:
    description: Transfer money to another player
    usage: /<command> [player] [amount]
  gamemode:
    description: Change a players gamemode
    usage: /<command> [mode] <player>
  gm:
    description: Change a players gamemode
    usage: /<command> [mode] <player>
  fill:
    description: Fill an area with a block
    usage: /<command> [block]
  /fill:
    description: Fill an area with a block
    usage: /<command> [block]
  set:
    description: Fill an area with a block
    usage: /<command> [block]
  /set:
    description: Fill an area with a block
    usage: /<command> [block]
  undo:
    description: Undo last eviledit event
    usage: /<command>
  /undo:
    description: Undo last eviledit event
    usage: /<command>
  rocket:
    description: Rocket a player
    usage: /<command> [player]
  slap:
    description: Slap a player
    usage: /<command> [player]
  shock:
    description: Shock a player
    usage: /<command> [player]
  tp:
    description: Teleport to a player
    usage: /<command> [player]
  teleport:
    description: Teleport to a player
    usage: /<command> [player]
  tphere:
    description: Teleport a player
    usage: /<command> [player]
  teleporthere:
    description: Teleport a player
    usage: /<command> [player]
  rename:
    description: Rename the player
    usage: /<command> [name]
  nick:
    description: Rename the player
    usage: /<command> [name]
  nickname:
    description: Rename the player
    usage: /<command> [name]
  mute:
    description: Mute a player
    usage: /<command> [player]
  ignore:
    description: Ignore a player
    usage: /<command> [player]
  unmute:
    description: Unmute a player
    usage: /<command> [player]
  vanish:
    description: Hide the player
    usage: /<command>
  hide:
    description: Hide the player
    usage: /<command>
  unvanish:
    description: Show the player
    usage: /<command>
  show:
    description: Show the player
    usage: /<command>
  clear:
    description: Clear the player inventory
    usage: /<command>
  dawn:
    description: Change the world time to dawn
    usage: /<command>
  day:
    description: Change the world time to day
    usage: /<command>
  dusk:
    description: Change the world time to dusk
    usage: /<command>
  night:
    description: Change the world time to night
    usage: /<command>
  clean:
    description: Clean the server of entities
    usage: /<command>
  kiss:
    description: Kiss a player
    usage: /<command> [player]
  hug:
    description: Hug a player
    usage: /<command> [player]
  tree:
    description: Spawn a tree
    usage: /<command> [type]
  colors:
    description: View the list of colors
    usage: /<command>
  colours:
    description: View the list of colors
    usage: /<command>
  ranks:
    description: View the list of ranks
    usage: /<command>
  rules:
    description: View the list of rules
    usage: /<command>
  butcher:
    description: Kill all alive animals in the players world
    usage: /<command>
  remove:
    description: Kill all alive animals in the players world
    usage: /<command>
  killall:
    description: Kill all alive animals in the players world
    usage: /<command>
  mobkill:
    description: Kill all alive animals in the players world
    usage: /<command>
  me:
    description: Display an emotion or action
    usage: /<command> [message]
  setspawn:
    description: Set the map spawn point
    usage: /<command>
  spawn:
    description: Teleport to the spawn
    usage: /<command>
  broadcast:
    description: Broadcast a server message
    usage: /<command> [message]
  say:
    description: Broadcast a server message
    usage: /<command> [message]
  msg:
    description: Send a private message to a player
    usage: /<command> [player] [message]
  time:
    description: Change the world time
    usage: /<command> [time]
  afk:
    description: Set the player status to AFK
    usage: /<command>
  away:
    description: Set the player status to AFK
    usage: /<command>
  sun:
    description: Change the world weather to sunny
    usage: /<command>
  rain:
    description: Change the world weather to rainy
    usage: /<command>
  storm:
    description: Change the world weather to stormy
    usage: /<command>
  promote:
    description: Promote a player
    usage: /<command> [player] <rank>
  demote:
    description: Demote a player
    usage: /<command> [player]
  back:
    description: Teleport back to your death position
    usage: /<command>
  return:
    description: Teleport back to your death position
    usage: /<command>
  list:
    description: List the online players
    usage: /<command>
  who:
    description: List the online players
    usage: /<command>
  playerlist:
    description: List the online players
    usage: /<command>
  online:
    description: List the online players
    usage: /<command>
  plist:
    description: List the online players
    usage: /<command>
  help:
    description: View the server help
    usage: /<command>
  donate:
    description: View the donation instructions
    usage: /<command>
  admin:
    description: View the donation instructions
    usage: /<command>
  makeadmin:
    description: Make a player admin
    usage: /<command> [player]
  kill:
    description: Kill the player
    usage: /<command>
  enchant:
    description: Enchant an item
    usage: /<command> [enchantmentID] [enchantmentLevel]
  setwarp:
    description: Set a warp
    usage: /<command> [warpName]
  createwarp:
    description: Set a warp
    usage: /<command> [warpName]
  warp:
    description: Teleport to a warp
    usage: /<command> [warpName]
  cspawn:
    description: Spawn creatures
    usage: /<command> [creature] [amount]
  spawncreature:
    description: Spawn creatures
    usage: /<command> [creature] [amount]
  mob:
    description: Spawn creatures
    usage: /<command> [creature] [amount]
  spawnmob:
    description: Spawn creatures
    usage: /<command> [creature] [amount]
  money:
    description: View a players account balance
    usage: /<command> <player>
  balance:
    description: View a players account balance
    usage: /<command> <player>
  bal:
    description: View a players account balance
    usage: /<command> <player>
  flatland:
    description: Teleport to flatland
    usage: /<command>
  skyland:
    description: Teleport to skyland
    usage: /<command>
  sky:
    description: Teleport to skyland
    usage: /<command>
  sethome:
    description: Set your home location
    usage: /<command>
  createhome:
    description: Set your home location
    usage: /<command>
  delhome:
    description: Remove your home location
    usage: /<command>
  remhome:
    description: Remove your home location
    usage: /<command>
  rmhome:
    description: Remove your home location
    usage: /<command>
  homes:
    description: Teleport to your home location
    usage: /<command>
  home:
    description: Teleport to your home location
    usage: /<command>
  give:
    description: Give an item to a player
    usage: /<command> [item] <amount> <data>
  item:
    description: Give an item to a player
    usage: /<command> [item] <amount> <data>
  del:
    description: Delete a given area
    usage: /<command>
  delete:
    description: Delete a given area
    usage: /<command>